server:
  port: 8080


spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/courses
    driver-class-name: com.mysql.jdbc.Driver
